[package]
name = "husky-hooks"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"] }
